// This file was generated by Cinnabar Forge Meta. Do not edit.

export default {
  "cinnabarMetaVersion": 1,
  "name": "Cinnabar Forge Meta",
  "description": "Configuration editor and version updater",
  "version": {
    "major": 0,
    "minor": 1,
    "patch": 0,
    "revision": 1,
    "text": "0.1.0",
    "timestamp": 1711026835
  },
  "stack": {
    "nodejs": {
      "package": "@cinnabar-forge/meta",
      "outputFile": [
        "src",
        "cinnabar.js"
      ]
    }
  }
};
