/* eslint-disable security/detect-object-injection */
/* eslint-disable security/detect-non-literal-fs-filename */
import fs from "fs";
import inquirer from "inquirer";
import path from "path";

import { getFullVersionText, updateVersion } from "./version.js";

const CINNABAR_FILE = "cinnabar.json";

/**
 *
 * @param folderPath
 */
export async function getCinnabarData(folderPath) {
  const cinnabarPath = path.join(folderPath, CINNABAR_FILE);
  let cinnabarData;

  try {
    cinnabarData = JSON.parse(fs.readFileSync(cinnabarPath, "utf8"));
  } catch (error) {
    cinnabarData = {};
  } finally {
    if (cinnabarData.version == null) {
      cinnabarData.version = {
        major: 0,
        minor: 0,
        patch: 0,
        revision: 0,
        text: "0.0.0",
        timestamp: 0,
      };
    }
    if (cinnabarData.stack == null) {
      cinnabarData.stack = {};
    }
  }

  return cinnabarData;
}

/**
 * Handle the main menu and actions for the cinnabar.json file.
 * @param {string} folderPath - The path to the folder containing the cinnabar.json file.
 */
export async function handleCinnabarFile(folderPath) {
  const cinnabarData = await getCinnabarData(folderPath);

  const mainChoices = [
    { name: "Exit", value: "exit" },
    { name: "Change name", value: "changeName" },
    { name: "Change description", value: "changeDescription" },
    { name: "Change node.js package name", value: "changeNodejsPackageName" },
    { name: "Update version", value: "updateVersion" },
  ];

  const { action } = await inquirer.prompt({
    choices: mainChoices,
    message: getFullVersionText(cinnabarData),
    name: "action",
    type: "list",
  });

  switch (action) {
    case "exit":
      return;
    case "changeName":
      await handleChange("name", cinnabarData);
      break;
    case "changeDescription":
      await handleChange("description", cinnabarData);
      break;
    case "changeNodejsPackageName":
      if (cinnabarData.stack.nodejs == null) {
        cinnabarData.stack.nodejs = {};
      }
      await handleChange("package", cinnabarData.stack.nodejs);
      break;
    case "updateVersion":
      await updateVersion(cinnabarData, folderPath);
      break;
  }

  writeToFiles(folderPath, cinnabarData);
  handleCinnabarFile(folderPath);
}

/**
 * @param {string} key
 * @param {object} data
 */
async function handleChange(key, data) {
  const current = data[key];
  const { newValue } = await inquirer.prompt({
    default: current,
    message: `Enter new ${key}:`,
    name: "newValue",
    type: "input",
  });

  data[key] = newValue;
}

/**
 *
 * @param folderPath
 * @param cinnabarData
 * @param newVersion
 */
export function writeToFiles(folderPath, cinnabarData, newVersion = null) {
  if (newVersion != null) {
    cinnabarData.version = newVersion;
  }

  fs.writeFileSync(
    path.join(folderPath, CINNABAR_FILE),
    JSON.stringify(cinnabarData, null, 2) + "\n",
    "utf8",
  );

  if (cinnabarData.stack.nodejs) {
    updateJavascriptFile(folderPath, cinnabarData, newVersion);
    updatePackageJson(folderPath, newVersion);
    updatePackageLockJson(folderPath, newVersion);
  }
}

/**
 *
 * @param folderPath
 * @param cinnabarData
 * @param newVersion
 */
function updateJavascriptFile(folderPath, cinnabarData, newVersion) {
  const fileName = cinnabarData.stack?.nodejs?.outputFile ?? ["cinnabar.js"];
  const filePath = path.join(folderPath, ...fileName);

  cinnabarData.version = newVersion;

  try {
    fs.writeFileSync(
      filePath,
      `// This file was generated by Cinnabar Forge Meta. Do not edit.\n\nexport default ${JSON.stringify(cinnabarData, null, 2)};\n`,
      "utf8",
    );
  } catch (error) {
    console.error(`Failed to update ${fileName}:`, error.message);
  }
}

/**
 *
 * @param folderPath
 * @param newVersion
 */
function updatePackageJson(folderPath, newVersion) {
  const fileName = "package.json";
  const filePath = path.join(folderPath, fileName);
  try {
    const data = JSON.parse(fs.readFileSync(filePath, "utf8"));
    data.version = newVersion.text;
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + "\n", "utf8");
  } catch (error) {
    console.error(`Failed to update ${fileName}:`, error.message);
  }
}

/**
 *
 * @param folderPath
 * @param newVersion
 */
function updatePackageLockJson(folderPath, newVersion) {
  const fileName = "package-lock.json";
  const filePath = path.join(folderPath, fileName);
  try {
    const data = JSON.parse(fs.readFileSync(filePath, "utf8"));
    data.version = newVersion.text;
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + "\n", "utf8");
  } catch (error) {
    console.error(`Failed to update ${fileName}:`, error.message);
  }
}
